[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "chromium", "xorg.xvfb"]

[phases.install]
cmds = [
    "chmod +x ./build.sh",
    "./build.sh"
]

[phases.build]
cmds = [
    "python3 -m pip install -r requirements.txt"
]
