[phases.setup]
nixPkgs = ["python3", "chromium", "xorg.xvfb"]

[phases.install]
cmds = [
    "chmod +x ./build.sh",
    "./build.sh"
]

[phases.build]
cmds = [
    "pip install -r requirements.txt"
]
