# Railway Configuration for Google Maps Scraper
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "chmod +x ./start.sh && ./start.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
PYTHONPATH = "/app:/app/app"
CHROME_BIN = "/usr/bin/google-chrome"
CHROMEDRIVER_PATH = "/usr/bin/chromedriver"
DISPLAY = ":99"
DEBIAN_FRONTEND = "noninteractive"