
[phases.setup]
nixPkgs = ["python39", "chromium"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "python start_railway.py"

[variables]
PYTHONPATH = "/app"
CHROME_BIN = "/nix/store/*/bin/chromium"
CHROMEDRIVER_PATH = "/nix/store/*/bin/chromedriver"
RAILWAY_ENVIRONMENT = "1"