
[phases.setup]
nixPkgs = ["python39", "chromium", "chromedriver-chromium"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT app:app --timeout 300 --workers 2"

[variables]
PYTHONPATH = "/app:/app/app"
CHROME_BIN = "/nix/store/*/bin/chromium"
CHROMEDRIVER_PATH = "/nix/store/*/bin/chromedriver"