
[phases.setup]
nixPkgs = ["...", "chromium"]

[phases.install]
cmds = [
    "curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o chrome.deb",
    "apt-get update",
    "apt-get install -y ./chrome.deb",
    "rm chrome.deb"
]