# Railway Configuration
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python start_railway.py"
healthcheckPath = "/test"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
PYTHONPATH = "/app:/app/app"
CHROME_BIN = "/usr/bin/google-chrome"
CHROMEDRIVER_PATH = "/usr/bin/chromedriver"