# Railway Configuration
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT app:app --timeout 300 --workers 2"
healthcheckPath = "/test"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
PYTHONPATH = "/app:/app/app"
CHROME_BIN = "/usr/bin/chromium"
CHROMEDRIVER_PATH = "/usr/bin/chromedriver"