# Railway Configuration
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python3 main.py"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[variables]
RAILWAY_ENVIRONMENT = "1"
PYTHONPATH = "/app"