# Render.com Configuration
services:
  - type: web
    name: orizon-scraper
    env: python
    plan: free
    buildCommand: pip install -r requirements-deploy.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 300 --workers 2
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src:/opt/render/project/src/app
      - key: CHROME_BIN
        value: /usr/bin/google-chrome
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver